name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checking out repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.PAT }}
      -
        name: Tests
        run: ./tests.sh
